[package]
name = "ark-hybrid-compression"
version = "0.0.1"
edition = "2024"
description = "Arkworks Hybrid Compression"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Robert-MacWha/ark-hybrid-profiler"
keywords = ["ark", "circuit", "snark"]
categories = ["cryptography"]
exclude = [".gitignore"]

[features]
default = []
alloy = ["alloy-primitives"]
test-utils = []

[dependencies]
alloy-primitives = { version = "1.7.1", default-features = false, optional = true }
ark-crypto-primitives = { version = "0.6.0", features = ["crh", "constraints"] }
ark-ff = "0.6.0"
ark-r1cs-std = "0.6.0"
ark-relations = "0.6.0"
ark-std = "0.6.0"
thiserror = "2"

[dev-dependencies]
alloy = { version = "2.4.1", features = ["node-bindings"] }
ark-ed-on-bn254 = "0.6.0"
ruint = { version = "1.20.1", features = ["ark-ff-06"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[test]]
name = "solidity_parity"
path = "tests/solidity_parity.rs"
required-features = ["alloy"]

[[test]]
name = "circuit_integration"
path = "tests/circuit_integration.rs"
required-features = ["alloy", "test-utils"]
